import type { AssetLicence } from '@/models'

/**
 * Kenney's Tiny series: one artist and one palette across town, farm, battle
 * and dungeon, which is why the world and its people show no seam at 16px.
 * CC0 waives attribution; the credit is recorded as required anyway, because
 * naming the person who gave the art away costs nothing.
 */
function kenney(pack: string) {
  return {
    author: 'Kenney',
    source: `Kenney, ${pack} (kenney.nl)`,
    licence: 'CC0-1.0',
    attribution: `${pack} art by Kenney (kenney.nl)`
  } as const
}

/**
 * Every art asset, and where it came from. The guard tests read this manifest
 * against both art paths, so a file dropped in without an entry fails by name
 * before it can reach a page.
 *
 * Paths are relative to `src/assets/`, so the illustrated and sprite paths
 * share one namespace. Keying them off the illustrated root worked only while
 * that was the sole path carrying art; a sprite could land unrecorded and no
 * guard would have looked.
 */
export const assetLicences: AssetLicence[] = [
  { file: 'sprites/tiles/town.png', ...kenney('Tiny Town') },
  { file: 'sprites/tiles/farm.png', ...kenney('Tiny Farm') },
  // The 3x3 water set cropped out of Tiny Battle; the rest of that sheet is
  // armies and is not shipped.
  { file: 'sprites/tiles/water.png', ...kenney('Tiny Battle') },
  // Which sprite depicts which person is the owner's recorded decision
  // (Tiny Dungeon tiles 85, 99 and 88), not something inferred from a name.
  { file: 'sprites/character/hero.png', ...kenney('Tiny Dungeon') },
  { file: 'sprites/character/npc-laura.png', ...kenney('Tiny Dungeon') },
  { file: 'sprites/character/npc-rivaldy.png', ...kenney('Tiny Dungeon') },
  // Generated by Petdex for the owner, so it takes the `owner` variant: no
  // source, no licence, no credit line. The entry exists anyway, because the
  // guard's job is to prove every file was considered, not only the borrowed
  // ones.
  { file: 'sprites/character/companion-pet.png', author: 'owner' }
]

/**
 * Default transferred-size ceiling per illustrated asset.
 *
 * 400 KB is roughly a full-bleed backdrop at 2x on a slow connection before it
 * starts to feel like a wait. An asset that genuinely earns more declares its
 * own `maxBytes` rather than raising the ceiling for everything.
 */
export const DEFAULT_MAX_BYTES = 400_000

/** Third-party entries that a licence obliges us to credit on the site. */
export function attributions(entries: AssetLicence[] = assetLicences) {
  return entries.filter((e) => e.author !== 'owner')
}
